### ISSUE TITLE
请问能否推出适用于1.7.10的mod版本

### ISSUE THREAD

**Issue by Taoist-Yu** [PorPit/MineCamera#1]
请问一下mod能不能推出1.7.10版本？

如果我想魔改一下让这个mod再1.7.10版本中运行，除了修改主类注解以外还需要什么吗？

**Comment by Taoist-Yu** [comment]
仅仅自己和同学联机使用，不转载

**Comment by PorPit** [comment]
首先  1.7.10 和  之后的版本差异比较大
如果要支持1.7.10 可能比较麻烦

目前暂没有支持1.7.10的打算

而且我也不推荐开1.7.10版本的MOD服
目前Sponge服务端已经很完善了
并且1.10.2-1.12.2版本mod 众多
基本上不考虑缺少mod

**Comment by PorPit** [comment]
如果你要魔改可能需要花很大的功夫(其实我不移植也是因为这个原因2333)
