### ISSUE TITLE
[Suggestion] 一些修改建议

### ISSUE THREAD

**Issue by TartaricAcid** [PorPit/MineCamera#2]
你好，我在使用这个模组过程中有一些建议想要反馈下，希望这些建议能够为你带来帮助和改善：

### 1. 标点符号问题
游戏语言文件大量使用了英文标点符号。

![20180617172811.png](https://i.loli.net/2018/06/17/5b2629e808777.png)

### 2. gui 大小问题
在小窗口下，屏幕中图片大小失衡

![20180617192507.png](https://i.loli.net/2018/06/17/5b264524a1c78.png)

### 3. 玩家快捷不隐藏问题
打开GUI情况下，原版状态栏和快捷栏应当隐藏

![20180617192656.png](https://i.loli.net/2018/06/17/5b26458b6056c.png)

**Comment by PorPit** [comment]
emmm英文标点纯属习惯。。
至于GUI问题  确实需要完善一下
谢谢建议

**Comment by PorPit** [comment]
gui问题应该已经完善
