### ISSUE TITLE
[BUG] Shfit 点击放置物品导致崩溃

### ISSUE THREAD

**Issue by TartaricAcid** [PorPit/MineCamera#3]
使用版本：`1.12.2.minecamera-beta_1.0.jar `
Forge 版本：`2705`
崩溃报告：<https://paste.ubuntu.com/p/8Tvkww2Y2c/>
可否复现：可以
具体原因：打开任意该模组 GUI，采用原版 Shift 点击方式放置物品，游戏闪退。

> 既然等了几天作者出现了，我就顺手再加个错误报告吧

**Comment by PorPit** [comment]
了解了    我有空修复一下

**Comment by PorPit** [comment]
已修复
