### ISSUE TITLE
sponge1.12.2 forge2705 拍照时客户端掉线

### ISSUE THREAD

**Issue by assidence** [PorPit/MineCamera#4]
您好，我正在用sponge1.12.2-2705-7.1.0-BETA-3361和forge2705开服，服务器安装minecamera后，玩家拍照时会掉线，服务器后台出现报错。
[latest.log](https://github.com/PorPit/MineCamera/files/2291037/latest.log)
望解决，作者辛苦了，感谢原创^^

**Comment by PorPit** [comment]
mod版本多少

**Comment by assidence** [comment]
mod版本是github上下载的1.12.2-minecamera-1.1.0

**Comment by PorPit** [comment]
找到原因了  今天晚上发布修复

**Comment by PorPit** [comment]
用摄影架拍摄的时候掉线对吧

**Comment by assidence** [comment]
是的，作者辛苦了^ ^

**Comment by PorPit** [comment]
已修复
