### ISSUE TITLE
Bugs found in minecamera 

### ISSUE THREAD

**Issue by Titoo8899** [PorPit/MineCamera#5]
I have found two little bug with the camera with tripod. Then you have place it and go in this camara you can not go out and the other bug is then you destroy ´the block under the tripod and the item plopp then can you not block place in this hole. 

 

The 1 bug have I not idear what I have false make why I can switch the modes in the camera with tripod but I can not exit this only kill or close Minecraft is the answer for me in this time please give me a answer what wrong was. And the other think please fix this then it is a bug.

**Comment by PorPit** [comment]
first one u just change to Mode:tripod and press Shift to leave tripod
the seconed one was bug i will try to fix it

**Comment by PorPit** [comment]
fixed
